-- Lua functions
local unpack = unpack

-- AddOn namespace
local _, Private = ...

-- ElvUI modules
local E = unpack(ElvUI)

function Private:Setup_ElvUI()
	Private:Setup_ElvUI_Profile()
	Private:Setup_ElvUI_PrivateDB()
	Private:Setup_ElvUI_GlobalDB()
	
	Private:Setup_ElvUI_WeakAuras()

	-- Update ElvUI
	E:StaggeredUpdateAll()

	-- Show message about layout being set
	PluginInstallStepComplete.message = "Layout Set"
	PluginInstallStepComplete:Show()
end

function Private:Setup_ElvUI_Profile()
	
	E.data:SetProfile('XvUI')
	-- AB conversion
	E.db["convertPages"] = true
	-- Protect movers error
	E.db.movers = E.db.movers or {}

	-- General
	E.db["general"]["addonCompartment"]["font"] = Private.Font
	E.db["general"]["addonCompartment"]["fontSize"] = 14
	E.db["general"]["addonCompartment"]["hide"] = true
	E.db["general"]["afk"] = false
	E.db["general"]["altPowerBar"]["font"] = Private.Font
	E.db["general"]["altPowerBar"]["statusBar"] = Private.Texture
	E.db["general"]["altPowerBar"]["statusBarColor"]["b"] = 0.80000007152557
	E.db["general"]["altPowerBar"]["statusBarColor"]["g"] = 0.40000003576279
	E.db["general"]["altPowerBar"]["statusBarColor"]["r"] = 0.20000001788139
	E.db["general"]["autoRepair"] = "PLAYER"
	E.db["general"]["backdropcolor"]["b"] = 0.2
	E.db["general"]["backdropcolor"]["g"] = 0.2
	E.db["general"]["backdropcolor"]["r"] = 0.2
	E.db["general"]["backdropfadecolor"]["a"] = 0.8
	E.db["general"]["backdropfadecolor"]["b"] = 0.1
	E.db["general"]["backdropfadecolor"]["g"] = 0.1
	E.db["general"]["backdropfadecolor"]["r"] = 0.1
	E.db["general"]["bonusObjectivePosition"] = "AUTO"
	E.db["general"]["bottomPanel"] = false
	E.db["general"]["font"] = Private.Font
	E.db["general"]["fontStyle"] = "SHADOW"
	E.db["general"]["fonts"]["cooldown"]["enable"] = false
	E.db["general"]["fonts"]["errortext"]["enable"] = false
	E.db["general"]["guildBank"]["countFont"] = Private.Font
	E.db["general"]["guildBank"]["countFontOutline"] = Private.Outline
	E.db["general"]["guildBank"]["countFontSize"] = 12
	E.db["general"]["guildBank"]["itemLevelFont"] = Private.Font
	E.db["general"]["guildBank"]["itemLevelFontOutline"] = Private.Outline
	E.db["general"]["guildBank"]["itemLevelFontSize"] = 12
	E.db["general"]["itemLevel"]["itemLevelFont"] = Private.Font
	E.db["general"]["itemLevel"]["itemLevelFontOutline"] = "SHADOW"
	E.db["general"]["itemLevel"]["totalLevelFont"] = Private.Font
	E.db["general"]["itemLevel"]["totalLevelFontOutline"] = "SHADOW"
	E.db["general"]["itemLevel"]["totalLevelFontSize"] = 18
	E.db["general"]["lootRoll"]["nameFont"] = Private.Font
	E.db["general"]["lootRoll"]["statusBarTexture"] = "XvUI"
	E.db["general"]["minimap"]["icons"]["calendar"]["scale"] = 1
	E.db["general"]["minimap"]["icons"]["calendar"]["xOffset"] = 3
	E.db["general"]["minimap"]["icons"]["calendar"]["yOffset"] = -3
	E.db["general"]["minimap"]["icons"]["crafting"]["position"] = "TOPLEFT"
	E.db["general"]["minimap"]["icons"]["crafting"]["xOffset"] = 3
	E.db["general"]["minimap"]["icons"]["mail"]["xOffset"] = -5
	E.db["general"]["minimap"]["icons"]["mail"]["yOffset"] = 0
	E.db["general"]["minimap"]["locationFont"] = "XvUI"
	E.db["general"]["minimap"]["locationFontOutline"] = "SHADOW"
	E.db["general"]["minimap"]["size"] = 220
	E.db["general"]["minimap"]["timeFont"] = Private.Font
	E.db["general"]["minimap"]["timeFontOutline"] = "SHADOW"
	E.db["general"]["objectiveFrameAutoHide"] = false
	E.db["general"]["objectiveFrameHeight"] = 400
	E.db["general"]["queueStatus"]["font"] = Private.Font
	E.db["general"]["queueStatus"]["fontSize"] = 12
	E.db["general"]["resurrectSound"] = true
	E.db["general"]["talkingHeadFrameScale"] = 1
	E.db["general"]["totems"]["growthDirection"] = "HORIZONTAL"
	E.db["general"]["totems"]["size"] = 50
	E.db["general"]["totems"]["sortDirection"] = "DESCENDING"
	E.db["general"]["totems"]["spacing"] = 8
	E.db["general"]["valuecolor"]["b"] = 0.9215686917305
	E.db["general"]["valuecolor"]["g"] = 0.78039222955704
	E.db["general"]["valuecolor"]["r"] = 0.24705883860588
	
	-- ActionBars
	E.db["actionbar"]["bar1"]["buttonSize"] = 36
	E.db["actionbar"]["bar1"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar1"]["countFont"] = Private.Font
	E.db["actionbar"]["bar1"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar1"]["countFontSize"] = 12
	E.db["actionbar"]["bar1"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar1"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar1"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar1"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar1"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar1"]["macroFontSize"] = 12
	E.db["actionbar"]["bar1"]["macrotext"] = true
	E.db["actionbar"]["bar1"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar1"]["macroTextYOffset"] = 0

	E.db["actionbar"]["bar2"]["buttonSize"] = 36
	E.db["actionbar"]["bar2"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar2"]["countFont"] = Private.Font
	E.db["actionbar"]["bar2"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar2"]["countFontSize"] = 12
	E.db["actionbar"]["bar2"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar2"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar2"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar2"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar2"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar2"]["macroFontSize"] = 12
	E.db["actionbar"]["bar2"]["macrotext"] = true
	E.db["actionbar"]["bar2"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar2"]["macroTextYOffset"] = 0

	E.db["actionbar"]["bar3"]["buttons"] = 12
	E.db["actionbar"]["bar3"]["buttonsPerRow"] = 12
	E.db["actionbar"]["bar3"]["buttonSize"] = 36
	E.db["actionbar"]["bar3"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar3"]["countFont"] = Private.Font
	E.db["actionbar"]["bar3"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar3"]["countFontSize"] = 12
	E.db["actionbar"]["bar3"]["enabled"] = true
	E.db["actionbar"]["bar3"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar3"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar3"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar3"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar3"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar3"]["macroFontSize"] = 12
	E.db["actionbar"]["bar3"]["macrotext"] = true
	E.db["actionbar"]["bar3"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar3"]["macroTextYOffset"] = 0

	E.db["actionbar"]["bar4"]["backdrop"] = false
	E.db["actionbar"]["bar4"]["buttonsPerRow"] = 12
	E.db["actionbar"]["bar4"]["buttonSize"] = 36
	E.db["actionbar"]["bar4"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar4"]["countFont"] = Private.Font
	E.db["actionbar"]["bar4"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar4"]["countFontSize"] = 12
	E.db["actionbar"]["bar4"]["enabled"] = true
	E.db["actionbar"]["bar4"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar4"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar4"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar4"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar4"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar4"]["macroFontSize"] = 12
	E.db["actionbar"]["bar4"]["macrotext"] = true
	E.db["actionbar"]["bar4"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar4"]["macroTextYOffset"] = 0
	E.db["actionbar"]["bar4"]["point"] = "BOTTOMLEFT"

	E.db["actionbar"]["bar5"]["buttons"] = 12
	E.db["actionbar"]["bar5"]["buttonsPerRow"] = 4
	E.db["actionbar"]["bar5"]["buttonSize"] = 36
	E.db["actionbar"]["bar5"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar5"]["countFont"] = Private.Font
	E.db["actionbar"]["bar5"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar5"]["countFontSize"] = 12
	E.db["actionbar"]["bar5"]["enabled"] = true
	E.db["actionbar"]["bar5"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar5"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar5"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar5"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar5"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar5"]["macroFontSize"] = 12
	E.db["actionbar"]["bar5"]["macrotext"] = true
	E.db["actionbar"]["bar5"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar5"]["macroTextYOffset"] = 0

	E.db["actionbar"]["bar6"]["buttons"] = 12
	E.db["actionbar"]["bar6"]["buttonsPerRow"] = 4
	E.db["actionbar"]["bar6"]["buttonSize"] = 36
	E.db["actionbar"]["bar6"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar6"]["countFont"] = Private.Font
	E.db["actionbar"]["bar6"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar6"]["countFontSize"] = 12
	E.db["actionbar"]["bar6"]["enabled"] = true
	E.db["actionbar"]["bar6"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar6"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar6"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar6"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar6"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar6"]["macroFontSize"] = 12
	E.db["actionbar"]["bar6"]["macrotext"] = true
	E.db["actionbar"]["bar6"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar6"]["macroTextYOffset"] = 0

	E.db["actionbar"]["bar7"]["buttonSize"] = 36
	E.db["actionbar"]["bar7"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar7"]["countFont"] = Private.Font
	E.db["actionbar"]["bar7"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar7"]["countFontSize"] = 12
	E.db["actionbar"]["bar7"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar7"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar7"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar7"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar7"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar7"]["macroFontSize"] = 12
	E.db["actionbar"]["bar7"]["macrotext"] = true
	E.db["actionbar"]["bar7"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar7"]["macroTextYOffset"] = 0

	E.db["actionbar"]["bar8"]["buttonSize"] = 36
	E.db["actionbar"]["bar8"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar8"]["countFont"] = Private.Font
	E.db["actionbar"]["bar8"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar8"]["countFontSize"] = 12
	E.db["actionbar"]["bar8"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar8"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar8"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar8"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar8"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar8"]["macroFontSize"] = 12
	E.db["actionbar"]["bar8"]["macrotext"] = true
	E.db["actionbar"]["bar8"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar8"]["macroTextYOffset"] = 0

	E.db["actionbar"]["bar9"]["buttonSize"] = 36
	E.db["actionbar"]["bar9"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar9"]["countFont"] = Private.Font
	E.db["actionbar"]["bar9"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar9"]["countFontSize"] = 12
	E.db["actionbar"]["bar9"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar9"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar9"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar9"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar9"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar9"]["macroFontSize"] = 12
	E.db["actionbar"]["bar9"]["macrotext"] = true
	E.db["actionbar"]["bar9"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar9"]["macroTextYOffset"] = 0

	E.db["actionbar"]["bar10"]["buttonSize"] = 36
	E.db["actionbar"]["bar10"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar10"]["countFont"] = Private.Font
	E.db["actionbar"]["bar10"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar10"]["countFontSize"] = 12
	E.db["actionbar"]["bar10"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar10"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar10"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar10"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar10"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar10"]["macroFontSize"] = 12
	E.db["actionbar"]["bar10"]["macrotext"] = true
	E.db["actionbar"]["bar10"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar10"]["macroTextYOffset"] = 0
	
	E.db["actionbar"]["bar13"]["buttonsPerRow"] = 4
	E.db["actionbar"]["bar13"]["buttonSize"] = 36
	E.db["actionbar"]["bar13"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar13"]["countFont"] = Private.Font
	E.db["actionbar"]["bar13"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar13"]["countFontSize"] = 12
	E.db["actionbar"]["bar13"]["enabled"] = true
	E.db["actionbar"]["bar13"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar13"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar13"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar13"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar13"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar13"]["macroFontSize"] = 12
	E.db["actionbar"]["bar13"]["macrotext"] = true
	E.db["actionbar"]["bar13"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar13"]["macroTextYOffset"] = 0

	E.db["actionbar"]["bar14"]["buttonsPerRow"] = 4
	E.db["actionbar"]["bar14"]["buttonSize"] = 36
	E.db["actionbar"]["bar14"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar14"]["countFont"] = Private.Font
	E.db["actionbar"]["bar14"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar14"]["countFontSize"] = 12
	E.db["actionbar"]["bar14"]["enabled"] = true
	E.db["actionbar"]["bar14"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar14"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar14"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar14"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar14"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar14"]["macroFontSize"] = 12
	E.db["actionbar"]["bar14"]["macrotext"] = true
	E.db["actionbar"]["bar14"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar14"]["macroTextYOffset"] = 0

	E.db["actionbar"]["bar15"]["buttons"] = 6
	E.db["actionbar"]["bar15"]["buttonsPerRow"] = 1
	E.db["actionbar"]["bar15"]["buttonSize"] = 36
	E.db["actionbar"]["bar15"]["buttonSpacing"] = 5
	E.db["actionbar"]["bar15"]["countFont"] = Private.Font
	E.db["actionbar"]["bar15"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["bar15"]["countFontSize"] = 12
	E.db["actionbar"]["bar15"]["enabled"] = true
	E.db["actionbar"]["bar15"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["bar15"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["bar15"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar15"]["macroFont"] = Private.Font
	E.db["actionbar"]["bar15"]["macroFontOutline"] = Private.Outline
	E.db["actionbar"]["bar15"]["macroFontSize"] = 12
	E.db["actionbar"]["bar15"]["macrotext"] = true
	E.db["actionbar"]["bar15"]["macroTextPosition"] = "BOTTOMRIGHT"
	E.db["actionbar"]["bar15"]["macroTextYOffset"] = 0
	E.db["actionbar"]["bar15"]["point"] = "TOPLEFT"
	
	E.db["actionbar"]["barPet"]["backdrop"] = false
	E.db["actionbar"]["barPet"]["buttonsPerRow"] = 10
	E.db["actionbar"]["barPet"]["buttonSize"] = 36
	E.db["actionbar"]["barPet"]["buttonSpacing"] = 5
	E.db["actionbar"]["barPet"]["countFont"] = Private.Font
	E.db["actionbar"]["barPet"]["countFontOutline"] = Private.Outline
	E.db["actionbar"]["barPet"]["countFontSize"] = 12
	E.db["actionbar"]["barPet"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["barPet"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["barPet"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["barPet"]["point"] = "BOTTOMLEFT"

	E.db["actionbar"]["extraActionButton"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["extraActionButton"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["extraActionButton"]["hotkeyFontSize"] = 12

	E.db["actionbar"]["font"] = Private.Font
	E.db["actionbar"]["fontOutline"] = Private.Outline
	E.db["actionbar"]["fontSize"] = 12

	E.db["actionbar"]["microbar"]["enabled"] = true
	E.db["actionbar"]["microbar"]["buttonHeight"] = 24
	E.db["actionbar"]["microbar"]["buttonSpacing"] = 1
	E.db["actionbar"]["microbar"]["useIcons"] = false

	E.db["actionbar"]["stanceBar"]["buttonSize"] = 36
	E.db["actionbar"]["stanceBar"]["buttonSpacing"] = 5
	E.db["actionbar"]["stanceBar"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["stanceBar"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["stanceBar"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["stanceBar"]["point"] = "BOTTOMLEFT"

	E.db["actionbar"]["vehicleExitButton"]["hotkeyFont"] = Private.Font
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFontOutline"] = Private.Outline
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["vehicleExitButton"]["size"] = 36

	E.db["actionbar"]["zoneActionButton"]["clean"] = true

	-- Auras
	E.db["auras"]["buffs"]["countFont"] = Private.Font
	E.db["auras"]["buffs"]["countFontOutline"] = Private.Outline
	E.db["auras"]["buffs"]["countFontSize"] = 12
	E.db["auras"]["buffs"]["horizontalSpacing"] = 4
	E.db["auras"]["buffs"]["size"] = 36
	E.db["auras"]["buffs"]["timeFont"] = Private.Font
	E.db["auras"]["buffs"]["timeFontOutline"] = Private.Outline
	E.db["auras"]["buffs"]["timeFontSize"] = 12

	E.db["auras"]["debuffs"]["countFont"] = Private.Font
	E.db["auras"]["debuffs"]["countFontOutline"] = Private.Outline
	E.db["auras"]["debuffs"]["countFontSize"] = 12
	E.db["auras"]["debuffs"]["horizontalSpacing"] = 4
	E.db["auras"]["debuffs"]["size"] = 36
	E.db["auras"]["debuffs"]["timeFont"] = Private.Font
	E.db["auras"]["debuffs"]["timeFontOutline"] = Private.Outline
	E.db["auras"]["debuffs"]["timeFontSize"] = 12
	
	-- Bags
	E.db["bags"]["autoToggle"]["guildBank"] = true
	E.db["bags"]["bagButtonSpacing"] = 3
	E.db["bags"]["bagSize"] = 36
	E.db["bags"]["bagWidth"] = 450
	E.db["bags"]["bankButtonSpacing"] = 3
	E.db["bags"]["bankSize"] = 36
	E.db["bags"]["bankWidth"] = 450
	E.db["bags"]["countFont"] = Private.Font
	E.db["bags"]["countFontOutline"] = Private.Outline
	E.db["bags"]["countFontSize"] = 12
	E.db["bags"]["itemInfoFont"] = Private.Font
	E.db["bags"]["itemInfoFontOutline"] = Private.Outline
	E.db["bags"]["itemInfoFontSize"] = 12
	E.db["bags"]["itemLevelFont"] = Private.Font
	E.db["bags"]["itemLevelFontOutline"] = Private.Outline
	E.db["bags"]["itemLevelFontSize"] = 12
	E.db["bags"]["junkDesaturate"] = true
	E.db["bags"]["junkIcon"] = true
	E.db["bags"]["showBindType"] = true
	E.db["bags"]["split"]["bag5"] = true
	E.db["bags"]["split"]["bagSpacing"] = 10
	E.db["bags"]["split"]["bankSpacing"] = 10
	E.db["bags"]["split"]["player"] = true
	E.db["bags"]["split"]["warbandSpacing"] = 10
	E.db["bags"]["vendorGrays"]["enable"] = true
	E.db["bags"]["vendorGrays"]["interval"] = 0.1
	E.db["bags"]["warbandButtonSpacing"] = 3
	E.db["bags"]["warbandCombined"] = false
	E.db["bags"]["warbandSize"] = 36
	E.db["bags"]["warbandWidth"] = 570

	-- Chat
	E.db["chat"]["font"] = Private.Font
	E.db["chat"]["fontSize"] = 12
	E.db["chat"]["historySize"] = 500
	E.db["chat"]["panelColor"]["a"] = 0.5
	E.db["chat"]["panelColor"]["b"] = 0.05
	E.db["chat"]["panelColor"]["g"] = 0.05
	E.db["chat"]["panelColor"]["r"] = 0.05
	E.db["chat"]["panelHeight"] = 200
	E.db["chat"]["panelWidth"] = 450
	E.db["chat"]["tabFont"] = Private.Font
	E.db["chat"]["tabSelectorColor"]["b"] = 0.9215686917305
	E.db["chat"]["tabSelectorColor"]["g"] = 0.78039222955704
	E.db["chat"]["tabSelectorColor"]["r"] = 0.24705883860588
	E.db["chat"]["timeStampFormat"] = "%H:%M "

	-- Cooldown Text
	E.db["cooldown"]["fonts"]["font"] = Private.Font
	E.db["cooldown"]["fonts"]["fontSize"] = 14
	E.db["cooldown"]["targetAura"] = false

	-- DataBars
	E.db["databars"]["azerite"]["enable"] = false
	E.db["databars"]["customTexture"] = true
	E.db["databars"]["experience"]["font"] = Private.Font
	E.db["databars"]["honor"]["enable"] = false
	E.db["databars"]["honor"]["font"] = Private.Font
	E.db["databars"]["honor"]["fontSize"] = 12
	E.db["databars"]["reputation"]["enable"] = true
	E.db["databars"]["reputation"]["font"] = Private.Font
	E.db["databars"]["reputation"]["fontSize"] = 12
	E.db["databars"]["statusbar"] = Private.Texture
	E.db["databars"]["threat"]["enable"] = false

	-- DataTexts default
	E.db["datatexts"]["battlePanel"]["LeftChatDataPanel"][1] = "Talent/Loot Specialization"
	E.db["datatexts"]["font"] = Private.Font
	E.db["datatexts"]["panels"]["LeftChatDataPanel"][3] = "QuickJoin"

	-- Tooltip
	E.db["tooltip"]["alwaysShowRealm"] = true
	E.db["tooltip"]["font"] = Private.Font
	E.db["tooltip"]["headerFont"] = Private.Font
	E.db["tooltip"]["headerFontSize"] = 12
	E.db["tooltip"]["healthBar"]["font"] = Private.Font
	E.db["tooltip"]["itemQuality"] = true
	E.db["tooltip"]["modifierID"] = "SHIFT"
	E.db["tooltip"]["mythicDataEnable"] = false
	E.db["tooltip"]["role"] = false
	E.db["tooltip"]["targetInfo"] = false

	E.db["unitframe"]["colors"]["auraBarBuff"]["b"] = 0.7294117808342
	E.db["unitframe"]["colors"]["auraBarBuff"]["g"] = 0.54901963472366
	E.db["unitframe"]["colors"]["auraBarBuff"]["r"] = 0.95686280727386
	E.db["unitframe"]["colors"]["castClassColor"] = true
	E.db["unitframe"]["colors"]["colorhealthbyvalue"] = false
	E.db["unitframe"]["colors"]["debuffHighlight"]["blendMode"] = "DISABLE"
	E.db["unitframe"]["colors"]["healthBreak"]["low"] = 0.35
	E.db["unitframe"]["colors"]["healthBreak"]["threshold"]["good"] = false
	E.db["unitframe"]["colors"]["healthBreak"]["threshold"]["neutral"] = false
	E.db["unitframe"]["colors"]["healthclass"] = true
	E.db["unitframe"]["colors"]["power"]["ALT_POWER"]["b"] = 1
	E.db["unitframe"]["colors"]["power"]["ALT_POWER"]["g"] = 0.50196081399918
	E.db["unitframe"]["colors"]["power"]["ALT_POWER"]["r"] = 0.25098040699959
	E.db["unitframe"]["colors"]["power"]["INSANITY"]["b"] = 1
	E.db["unitframe"]["colors"]["power"]["INSANITY"]["r"] = 0.50196081399918
	E.db["unitframe"]["colors"]["power"]["LUNAR_POWER"]["b"] = 1
	E.db["unitframe"]["colors"]["power"]["LUNAR_POWER"]["g"] = 0.57647061347961
	E.db["unitframe"]["colors"]["power"]["LUNAR_POWER"]["r"] = 0.33333334326744
	E.db["unitframe"]["colors"]["power"]["MANA"]["b"] = 1
	E.db["unitframe"]["colors"]["power"]["MANA"]["g"] = 0.71764707565308
	E.db["unitframe"]["colors"]["power"]["MANA"]["r"] = 0.49411767721176
	E.db["unitframe"]["colors"]["power"]["RAGE"]["b"] = 0.32156863808632
	E.db["unitframe"]["colors"]["power"]["RAGE"]["g"] = 0.32156863808632
	E.db["unitframe"]["colors"]["power"]["RAGE"]["r"] = 1
	E.db["unitframe"]["font"] = "XvUI"
	E.db["unitframe"]["fontOutline"] = "SHADOW"
	E.db["unitframe"]["fontSize"] = 16
	E.db["unitframe"]["maxAllowedGroups"] = false
	E.db["unitframe"]["statusbar"] = "XvUI"
	E.db["unitframe"]["units"]["arena"]["buffs"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["arena"]["buffs"]["xOffset"] = -5
	E.db["unitframe"]["units"]["arena"]["castbar"]["customTextFont"]["enable"] = true
	E.db["unitframe"]["units"]["arena"]["castbar"]["customTextFont"]["font"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["arena"]["castbar"]["customTextFont"]["fontSize"] = 14
	E.db["unitframe"]["units"]["arena"]["castbar"]["customTimeFont"]["enable"] = true
	E.db["unitframe"]["units"]["arena"]["castbar"]["customTimeFont"]["font"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["arena"]["castbar"]["customTimeFont"]["fontSize"] = 14
	E.db["unitframe"]["units"]["arena"]["castbar"]["height"] = 25
	E.db["unitframe"]["units"]["arena"]["castbar"]["positionsGroup"]["yOffset"] = -20
	E.db["unitframe"]["units"]["arena"]["castbar"]["width"] = 200
	E.db["unitframe"]["units"]["arena"]["debuffs"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["arena"]["debuffs"]["priority"] = "Blacklist,Boss,RaidDebuffs,Personal,CCDebuffs,Whitelist"
	E.db["unitframe"]["units"]["arena"]["debuffs"]["xOffset"] = -5
	E.db["unitframe"]["units"]["arena"]["healPrediction"]["absorbStyle"] = "WRAPPED"
	E.db["unitframe"]["units"]["arena"]["health"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["arena"]["health"]["position"] = "BOTTOMLEFT"
	E.db["unitframe"]["units"]["arena"]["health"]["text_format"] = "[perhp<%] || [health:current-nostatus:shortvalue]"
	E.db["unitframe"]["units"]["arena"]["health"]["yOffset"] = -20
	E.db["unitframe"]["units"]["arena"]["height"] = 45
	E.db["unitframe"]["units"]["arena"]["name"]["position"] = "RIGHT"
	E.db["unitframe"]["units"]["arena"]["name"]["text_format"] = " [arenaspec] - [name:medium]"
	E.db["unitframe"]["units"]["arena"]["name"]["xOffset"] = -10
	E.db["unitframe"]["units"]["arena"]["orientation"] = "LEFT"
	E.db["unitframe"]["units"]["arena"]["power"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["arena"]["power"]["height"] = 7
	E.db["unitframe"]["units"]["arena"]["power"]["position"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["arena"]["power"]["text_format"] = "[powercolor][perpp<%]"
	E.db["unitframe"]["units"]["arena"]["power"]["width"] = "spaced"
	E.db["unitframe"]["units"]["arena"]["power"]["xOffset"] = 0
	E.db["unitframe"]["units"]["arena"]["power"]["yOffset"] = -20
	E.db["unitframe"]["units"]["arena"]["pvpSpecIcon"] = false
	E.db["unitframe"]["units"]["arena"]["pvpTrinket"]["size"] = 36
	E.db["unitframe"]["units"]["arena"]["pvpTrinket"]["xOffset"] = 5
	E.db["unitframe"]["units"]["arena"]["pvpTrinket"]["yOffset"] = 2
	E.db["unitframe"]["units"]["arena"]["spacing"] = 50
	E.db["unitframe"]["units"]["arena"]["width"] = 200
	E.db["unitframe"]["units"]["assist"]["enable"] = false
	E.db["unitframe"]["units"]["boss"]["buffs"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["boss"]["buffs"]["maxDuration"] = 300
	E.db["unitframe"]["units"]["boss"]["buffs"]["perrow"] = 6
	E.db["unitframe"]["units"]["boss"]["buffs"]["sizeOverride"] = 0
	E.db["unitframe"]["units"]["boss"]["buffs"]["spacing"] = -1
	E.db["unitframe"]["units"]["boss"]["buffs"]["xOffset"] = -5
	E.db["unitframe"]["units"]["boss"]["buffs"]["yOffset"] = 0
	E.db["unitframe"]["units"]["boss"]["castbar"]["customTextFont"]["enable"] = true
	E.db["unitframe"]["units"]["boss"]["castbar"]["customTextFont"]["font"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["boss"]["castbar"]["customTextFont"]["fontSize"] = 14
	E.db["unitframe"]["units"]["boss"]["castbar"]["customTimeFont"]["enable"] = true
	E.db["unitframe"]["units"]["boss"]["castbar"]["customTimeFont"]["font"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["boss"]["castbar"]["customTimeFont"]["fontSize"] = 14
	E.db["unitframe"]["units"]["boss"]["castbar"]["enable"] = false
	E.db["unitframe"]["units"]["boss"]["castbar"]["height"] = 25
	E.db["unitframe"]["units"]["boss"]["castbar"]["width"] = 200
	E.db["unitframe"]["units"]["boss"]["debuffs"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["boss"]["debuffs"]["enable"] = false
	E.db["unitframe"]["units"]["boss"]["debuffs"]["maxDuration"] = 300
	E.db["unitframe"]["units"]["boss"]["debuffs"]["sizeOverride"] = 27
	E.db["unitframe"]["units"]["boss"]["debuffs"]["xOffset"] = -5
	E.db["unitframe"]["units"]["boss"]["debuffs"]["yOffset"] = -16
	E.db["unitframe"]["units"]["boss"]["health"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["boss"]["health"]["position"] = "BOTTOMLEFT"
	E.db["unitframe"]["units"]["boss"]["health"]["text_format"] = "[perhp<%] || [health:current-nostatus:shortvalue]"
	E.db["unitframe"]["units"]["boss"]["health"]["xOffset"] = 0
	E.db["unitframe"]["units"]["boss"]["health"]["yOffset"] = -20
	E.db["unitframe"]["units"]["boss"]["height"] = 45
	E.db["unitframe"]["units"]["boss"]["infoPanel"]["height"] = 17
	E.db["unitframe"]["units"]["boss"]["name"]["position"] = "RIGHT"
	E.db["unitframe"]["units"]["boss"]["name"]["text_format"] = "[name:abbrev]"
	E.db["unitframe"]["units"]["boss"]["name"]["xOffset"] = -10
	E.db["unitframe"]["units"]["boss"]["orientation"] = "LEFT"
	E.db["unitframe"]["units"]["boss"]["power"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["boss"]["power"]["height"] = 7
	E.db["unitframe"]["units"]["boss"]["power"]["position"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["boss"]["power"]["text_format"] = "[powercolor][perpp<%]"
	E.db["unitframe"]["units"]["boss"]["power"]["width"] = "spaced"
	E.db["unitframe"]["units"]["boss"]["power"]["xOffset"] = 0
	E.db["unitframe"]["units"]["boss"]["power"]["yOffset"] = -20
	E.db["unitframe"]["units"]["boss"]["width"] = 200
	E.db["unitframe"]["units"]["focus"]["aurabar"]["detachedWidth"] = 270
	E.db["unitframe"]["units"]["focus"]["aurabar"]["maxBars"] = 6
	E.db["unitframe"]["units"]["focus"]["buffIndicator"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["focus"]["buffIndicator"]["enable"] = true
	E.db["unitframe"]["units"]["focus"]["buffIndicator"]["size"] = 10
	E.db["unitframe"]["units"]["focus"]["buffs"]["priority"] = "Blacklist,Personal,PlayerBuffs,Dispellable"
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["font"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["fontSize"] = 14
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["fontStyle"] = "SHADOW"
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["font"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["fontSize"] = 14
	E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["fontStyle"] = "SHADOW"
	E.db["unitframe"]["units"]["focus"]["castbar"]["enable"] = false
	E.db["unitframe"]["units"]["focus"]["castbar"]["height"] = 25
	E.db["unitframe"]["units"]["focus"]["castbar"]["insideInfoPanel"] = false
	E.db["unitframe"]["units"]["focus"]["castbar"]["textColor"]["b"] = 1
	E.db["unitframe"]["units"]["focus"]["castbar"]["textColor"]["g"] = 1
	E.db["unitframe"]["units"]["focus"]["castbar"]["textColor"]["r"] = 1
	E.db["unitframe"]["units"]["focus"]["castbar"]["width"] = 135
	E.db["unitframe"]["units"]["focus"]["debuffs"]["anchorPoint"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["focus"]["debuffs"]["attachTo"] = "BUFFS"
	E.db["unitframe"]["units"]["focus"]["debuffs"]["enable"] = false
	E.db["unitframe"]["units"]["focus"]["debuffs"]["priority"] = "Blacklist,Personal,Boss,RaidDebuffs,CCDebuffs,Dispellable,Whitelist"
	E.db["unitframe"]["units"]["focus"]["disableMouseoverGlow"] = true
	E.db["unitframe"]["units"]["focus"]["disableTargetGlow"] = true
	E.db["unitframe"]["units"]["focus"]["healPrediction"]["enable"] = false
	E.db["unitframe"]["units"]["focus"]["height"] = 30
	E.db["unitframe"]["units"]["focus"]["name"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["focus"]["name"]["text_format"] = "[name:abbrev:long]"
	E.db["unitframe"]["units"]["focus"]["name"]["xOffset"] = 10
	E.db["unitframe"]["units"]["focus"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["focus"]["raidicon"]["attachTo"] = "LEFT"
	E.db["unitframe"]["units"]["focus"]["raidicon"]["enable"] = false
	E.db["unitframe"]["units"]["focus"]["raidicon"]["xOffset"] = 2
	E.db["unitframe"]["units"]["focus"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["focus"]["width"] = 135
	E.db["unitframe"]["units"]["focustarget"]["buffs"]["priority"] = "Blacklist,Personal,PlayerBuffs,Dispellable"
	E.db["unitframe"]["units"]["focustarget"]["debuffs"]["attachTo"] = "BUFFS"
	E.db["unitframe"]["units"]["focustarget"]["debuffs"]["priority"] = "Blacklist,Personal,Boss,RaidDebuffs,CCDebuffs,Dispellable,Whitelist"
	E.db["unitframe"]["units"]["focustarget"]["disableMouseoverGlow"] = true
	E.db["unitframe"]["units"]["focustarget"]["disableTargetGlow"] = true
	E.db["unitframe"]["units"]["focustarget"]["healPrediction"]["enable"] = false
	E.db["unitframe"]["units"]["focustarget"]["height"] = 40
	E.db["unitframe"]["units"]["focustarget"]["infoPanel"]["height"] = 14
	E.db["unitframe"]["units"]["focustarget"]["name"]["text_format"] = "[name:medium]"
	E.db["unitframe"]["units"]["focustarget"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["focustarget"]["raidicon"]["attachTo"] = "LEFT"
	E.db["unitframe"]["units"]["focustarget"]["raidicon"]["enable"] = false
	E.db["unitframe"]["units"]["focustarget"]["raidicon"]["xOffset"] = 2
	E.db["unitframe"]["units"]["focustarget"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["focustarget"]["threatStyle"] = "GLOW"
	E.db["unitframe"]["units"]["focustarget"]["width"] = 250
	E.db["unitframe"]["units"]["party"]["buffIndicator"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["party"]["buffIndicator"]["size"] = 10
	E.db["unitframe"]["units"]["party"]["buffs"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["party"]["buffs"]["perrow"] = 6
	E.db["unitframe"]["units"]["party"]["buffs"]["priority"] = "Blacklist,TurtleBuffs,PlayerBuffs"
	E.db["unitframe"]["units"]["party"]["buffs"]["xOffset"] = -5
	E.db["unitframe"]["units"]["party"]["debuffs"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["party"]["debuffs"]["perrow"] = 6
	E.db["unitframe"]["units"]["party"]["debuffs"]["sizeOverride"] = 0
	E.db["unitframe"]["units"]["party"]["debuffs"]["spacing"] = -1
	E.db["unitframe"]["units"]["party"]["debuffs"]["xOffset"] = 5
	E.db["unitframe"]["units"]["party"]["groupBy"] = "ROLE"
	E.db["unitframe"]["units"]["party"]["healPrediction"]["absorbStyle"] = "WRAPPED"
	E.db["unitframe"]["units"]["party"]["healPrediction"]["enable"] = true
	E.db["unitframe"]["units"]["party"]["health"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["party"]["health"]["position"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["party"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["party"]["health"]["xOffset"] = 0
	E.db["unitframe"]["units"]["party"]["health"]["yOffset"] = -20
	E.db["unitframe"]["units"]["party"]["height"] = 45
	E.db["unitframe"]["units"]["party"]["name"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["party"]["name"]["text_format"] = "[name:medium:status]"
	E.db["unitframe"]["units"]["party"]["name"]["xOffset"] = 10
	E.db["unitframe"]["units"]["party"]["orientation"] = "RIGHT"
	E.db["unitframe"]["units"]["party"]["petsGroup"]["disableFocusGlow"] = false
	E.db["unitframe"]["units"]["party"]["petsGroup"]["disableTargetGlow"] = false
	E.db["unitframe"]["units"]["party"]["power"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["party"]["power"]["position"] = "BOTTOMLEFT"
	E.db["unitframe"]["units"]["party"]["power"]["text_format"] = ""
	E.db["unitframe"]["units"]["party"]["power"]["width"] = "spaced"
	E.db["unitframe"]["units"]["party"]["power"]["xOffset"] = 0
	E.db["unitframe"]["units"]["party"]["power"]["yOffset"] = -20
	E.db["unitframe"]["units"]["party"]["raidRoleIcons"]["xOffset"] = 6
	E.db["unitframe"]["units"]["party"]["raidRoleIcons"]["yOffset"] = 3
	E.db["unitframe"]["units"]["party"]["rdebuffs"]["font"] = "XvUI"
	E.db["unitframe"]["units"]["party"]["rdebuffs"]["size"] = 24
	E.db["unitframe"]["units"]["party"]["rdebuffs"]["yOffset"] = 12
	E.db["unitframe"]["units"]["party"]["readycheckIcon"]["position"] = "CENTER"
	E.db["unitframe"]["units"]["party"]["readycheckIcon"]["size"] = 20
	E.db["unitframe"]["units"]["party"]["readycheckIcon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["party"]["roleIcon"]["attachTo"] = "Frame"
	E.db["unitframe"]["units"]["party"]["roleIcon"]["position"] = "TOPLEFT"
	E.db["unitframe"]["units"]["party"]["roleIcon"]["size"] = 16
	E.db["unitframe"]["units"]["party"]["roleIcon"]["xOffset"] = -8
	E.db["unitframe"]["units"]["party"]["roleIcon"]["yOffset"] = 8
	E.db["unitframe"]["units"]["party"]["sortDir"] = "DESC"
	E.db["unitframe"]["units"]["party"]["targetsGroup"]["disableFocusGlow"] = false
	E.db["unitframe"]["units"]["party"]["targetsGroup"]["disableTargetGlow"] = false
	E.db["unitframe"]["units"]["party"]["verticalSpacing"] = 10
	E.db["unitframe"]["units"]["party"]["width"] = 200
	E.db["unitframe"]["units"]["pet"]["aurabar"]["attachTo"] = "DEBUFFS"
	E.db["unitframe"]["units"]["pet"]["aurabar"]["detachedWidth"] = 270
	E.db["unitframe"]["units"]["pet"]["aurabar"]["priority"] = "Blacklist,blockNoDuration,Personal,Boss,RaidDebuffs,PlayerBuffs"
	E.db["unitframe"]["units"]["pet"]["aurabar"]["spacing"] = 0
	E.db["unitframe"]["units"]["pet"]["aurabar"]["yOffset"] = 0
	E.db["unitframe"]["units"]["pet"]["buffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["pet"]["buffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["pet"]["buffs"]["perrow"] = 8
	E.db["unitframe"]["units"]["pet"]["buffs"]["priority"] = "blockNoDuration,Blacklist,Personal,nonPersonal"
	E.db["unitframe"]["units"]["pet"]["castbar"]["enable"] = false
	E.db["unitframe"]["units"]["pet"]["castbar"]["height"] = 40
	E.db["unitframe"]["units"]["pet"]["castbar"]["insideInfoPanel"] = false
	E.db["unitframe"]["units"]["pet"]["castbar"]["width"] = 405
	E.db["unitframe"]["units"]["pet"]["debuffs"]["anchorPoint"] = "RIGHT"
	E.db["unitframe"]["units"]["pet"]["debuffs"]["attachTo"] = "BUFFS"
	E.db["unitframe"]["units"]["pet"]["debuffs"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["pet"]["debuffs"]["growthX"] = "RIGHT"
	E.db["unitframe"]["units"]["pet"]["debuffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["pet"]["debuffs"]["perrow"] = 4
	E.db["unitframe"]["units"]["pet"]["debuffs"]["priority"] = "Blacklist,Personal,nonPersonal"
	E.db["unitframe"]["units"]["pet"]["debuffs"]["sizeOverride"] = 32
	E.db["unitframe"]["units"]["pet"]["debuffs"]["spacing"] = 3
	E.db["unitframe"]["units"]["pet"]["debuffs"]["xOffset"] = 75
	E.db["unitframe"]["units"]["pet"]["debuffs"]["yOffset"] = 13
	E.db["unitframe"]["units"]["pet"]["disableMouseoverGlow"] = true
	E.db["unitframe"]["units"]["pet"]["healPrediction"]["absorbStyle"] = "WRAPPED"
	E.db["unitframe"]["units"]["pet"]["healPrediction"]["enable"] = false
	E.db["unitframe"]["units"]["pet"]["health"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["pet"]["health"]["position"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["pet"]["health"]["xOffset"] = 0
	E.db["unitframe"]["units"]["pet"]["health"]["yOffset"] = -20
	E.db["unitframe"]["units"]["pet"]["height"] = 30
	E.db["unitframe"]["units"]["pet"]["infoPanel"]["height"] = 20
	E.db["unitframe"]["units"]["pet"]["name"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["pet"]["name"]["text_format"] = "[name:medium]"
	E.db["unitframe"]["units"]["pet"]["name"]["xOffset"] = 10
	E.db["unitframe"]["units"]["pet"]["orientation"] = "RIGHT"
	E.db["unitframe"]["units"]["pet"]["power"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["pet"]["power"]["detachedWidth"] = 100
	E.db["unitframe"]["units"]["pet"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["pet"]["power"]["height"] = 7
	E.db["unitframe"]["units"]["pet"]["power"]["position"] = "BOTTOMLEFT"
	E.db["unitframe"]["units"]["pet"]["power"]["width"] = "spaced"
	E.db["unitframe"]["units"]["pet"]["power"]["xOffset"] = 0
	E.db["unitframe"]["units"]["pet"]["power"]["yOffset"] = -20
	E.db["unitframe"]["units"]["pet"]["width"] = 150
	E.db["unitframe"]["units"]["player"]["RestIcon"]["anchorPoint"] = "LEFT"
	E.db["unitframe"]["units"]["player"]["RestIcon"]["size"] = 27
	E.db["unitframe"]["units"]["player"]["RestIcon"]["xOffset"] = 0
	E.db["unitframe"]["units"]["player"]["RestIcon"]["yOffset"] = 20
	E.db["unitframe"]["units"]["player"]["aurabar"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["buffs"]["anchorPoint"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["player"]["buffs"]["attachTo"] = "FRAME"
	E.db["unitframe"]["units"]["player"]["buffs"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["player"]["buffs"]["enable"] = true
	E.db["unitframe"]["units"]["player"]["buffs"]["growthX"] = "LEFT"
	E.db["unitframe"]["units"]["player"]["buffs"]["height"] = 24
	E.db["unitframe"]["units"]["player"]["buffs"]["priority"] = "blockNoDuration,Blacklist,Whitelist,PlayerBuffs,TurtleBuffs"
	E.db["unitframe"]["units"]["player"]["castbar"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["castbar"]["height"] = 25
	E.db["unitframe"]["units"]["player"]["castbar"]["insideInfoPanel"] = false
	E.db["unitframe"]["units"]["player"]["castbar"]["textColor"]["b"] = 1
	E.db["unitframe"]["units"]["player"]["castbar"]["textColor"]["g"] = 1
	E.db["unitframe"]["units"]["player"]["castbar"]["textColor"]["r"] = 1
	E.db["unitframe"]["units"]["player"]["castbar"]["width"] = 250
	E.db["unitframe"]["units"]["player"]["classbar"]["detachFromFrame"] = true
	E.db["unitframe"]["units"]["player"]["classbar"]["detachedWidth"] = 220
	E.db["unitframe"]["units"]["player"]["classbar"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["classbar"]["fill"] = "spaced"
	E.db["unitframe"]["units"]["player"]["classbar"]["height"] = 9
	E.db["unitframe"]["units"]["player"]["classbar"]["spacing"] = 3
	E.db["unitframe"]["units"]["player"]["classbar"]["strataAndLevel"]["frameLevel"] = 2
	E.db["unitframe"]["units"]["player"]["classbar"]["strataAndLevel"]["frameStrata"] = "MEDIUM"
	E.db["unitframe"]["units"]["player"]["classbar"]["strataAndLevel"]["useCustomStrata"] = true
	E.db["unitframe"]["units"]["player"]["customTexts"] = {}
	E.db["unitframe"]["units"]["player"]["customTexts"]["Absorb"] = {
		["attachTextTo"] = "Health",
		["enable"] = true,
		["font"] = "FRIZQT__",
		["fontOutline"] = "SHADOW",
		["justifyH"] = "RIGHT",
		["size"] = 16,
		["text_format"] = "[absorbs]",
		["xOffset"] = -10,
		["yOffset"] = 0
	}
	E.db["unitframe"]["units"]["player"]["debuffs"]["anchorPoint"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["player"]["debuffs"]["attachTo"] = "BUFFS"
	E.db["unitframe"]["units"]["player"]["debuffs"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["player"]["debuffs"]["growthX"] = "LEFT"
	E.db["unitframe"]["units"]["player"]["debuffs"]["height"] = 24
	E.db["unitframe"]["units"]["player"]["debuffs"]["spacing"] = 0
	E.db["unitframe"]["units"]["player"]["disableMouseoverGlow"] = true
	E.db["unitframe"]["units"]["player"]["healPrediction"]["absorbStyle"] = "WRAPPED"
	E.db["unitframe"]["units"]["player"]["health"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["player"]["health"]["position"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["player"]["health"]["text_format"] = "[health:current-nostatus:shortvalue] || [perhp<%]"
	E.db["unitframe"]["units"]["player"]["health"]["xOffset"] = 0
	E.db["unitframe"]["units"]["player"]["health"]["yOffset"] = -20
	E.db["unitframe"]["units"]["player"]["height"] = 45
	E.db["unitframe"]["units"]["player"]["name"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["player"]["name"]["text_format"] = "[name:medium]"
	E.db["unitframe"]["units"]["player"]["name"]["xOffset"] = 10
	E.db["unitframe"]["units"]["player"]["orientation"] = "RIGHT"
	E.db["unitframe"]["units"]["player"]["portrait"]["fullOverlay"] = true
	E.db["unitframe"]["units"]["player"]["portrait"]["overlay"] = true
	E.db["unitframe"]["units"]["player"]["portrait"]["paused"] = true
	E.db["unitframe"]["units"]["player"]["power"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["player"]["power"]["detachFromFrame"] = true
	E.db["unitframe"]["units"]["player"]["power"]["detachedWidth"] = 120
	E.db["unitframe"]["units"]["player"]["power"]["height"] = 7
	E.db["unitframe"]["units"]["player"]["power"]["position"] = "BOTTOMLEFT"
	E.db["unitframe"]["units"]["player"]["power"]["strataAndLevel"]["frameStrata"] = "MEDIUM"
	E.db["unitframe"]["units"]["player"]["power"]["text_format"] = "[powercolor][perpp<%]"
	E.db["unitframe"]["units"]["player"]["power"]["width"] = "spaced"
	E.db["unitframe"]["units"]["player"]["power"]["xOffset"] = 0
	E.db["unitframe"]["units"]["player"]["power"]["yOffset"] = -20
	E.db["unitframe"]["units"]["player"]["raidRoleIcons"]["xOffset"] = 6
	E.db["unitframe"]["units"]["player"]["raidRoleIcons"]["yOffset"] = 3
	E.db["unitframe"]["units"]["player"]["width"] = 250
	E.db["unitframe"]["units"]["raid1"]["ROLE1"] = "HEALER"
	E.db["unitframe"]["units"]["raid1"]["ROLE2"] = "TANK"
	E.db["unitframe"]["units"]["raid1"]["buffIndicator"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["raid1"]["groupBy"] = "ROLE"
	E.db["unitframe"]["units"]["raid1"]["growthDirection"] = "LEFT_UP"
	E.db["unitframe"]["units"]["raid1"]["healPrediction"]["absorbStyle"] = "WRAPPED"
	E.db["unitframe"]["units"]["raid1"]["healPrediction"]["enable"] = true
	E.db["unitframe"]["units"]["raid1"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["raid1"]["height"] = 40
	E.db["unitframe"]["units"]["raid1"]["name"]["text_format"] = "[name:short:status]"
	E.db["unitframe"]["units"]["raid1"]["numGroups"] = 8
	E.db["unitframe"]["units"]["raid1"]["orientation"] = "RIGHT"
	E.db["unitframe"]["units"]["raid1"]["power"]["width"] = "spaced"
	E.db["unitframe"]["units"]["raid1"]["raidRoleIcons"]["xOffset"] = 6
	E.db["unitframe"]["units"]["raid1"]["raidRoleIcons"]["yOffset"] = 3
	E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["font"] = "XvUI"
	E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["size"] = 24
	E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["yOffset"] = 10
	E.db["unitframe"]["units"]["raid1"]["readycheckIcon"]["position"] = "CENTER"
	E.db["unitframe"]["units"]["raid1"]["readycheckIcon"]["size"] = 20
	E.db["unitframe"]["units"]["raid1"]["readycheckIcon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raid1"]["roleIcon"]["attachTo"] = "Frame"
	E.db["unitframe"]["units"]["raid1"]["roleIcon"]["position"] = "TOPLEFT"
	E.db["unitframe"]["units"]["raid1"]["roleIcon"]["size"] = 16
	E.db["unitframe"]["units"]["raid1"]["roleIcon"]["xOffset"] = -8
	E.db["unitframe"]["units"]["raid1"]["roleIcon"]["yOffset"] = 8
	E.db["unitframe"]["units"]["raid1"]["sortDir"] = "DESC"
	E.db["unitframe"]["units"]["raid1"]["visibility"] = "[@raid6,noexists][@raid31,exists] hide;show"
	E.db["unitframe"]["units"]["raid1"]["width"] = 100
	E.db["unitframe"]["units"]["raid2"]["enable"] = false
	E.db["unitframe"]["units"]["raid2"]["growthDirection"] = "RIGHT_UP"
	E.db["unitframe"]["units"]["raid2"]["healPrediction"]["absorbStyle"] = "WRAPPED"
	E.db["unitframe"]["units"]["raid2"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["raid2"]["height"] = 40
	E.db["unitframe"]["units"]["raid2"]["name"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["raid2"]["name"]["text_format"] = "[name:short:status]"
	E.db["unitframe"]["units"]["raid2"]["name"]["xOffset"] = 10
	E.db["unitframe"]["units"]["raid2"]["numGroups"] = 8
	E.db["unitframe"]["units"]["raid2"]["orientation"] = "RIGHT"
	E.db["unitframe"]["units"]["raid2"]["power"]["enable"] = true
	E.db["unitframe"]["units"]["raid2"]["power"]["width"] = "spaced"
	E.db["unitframe"]["units"]["raid2"]["raidRoleIcons"]["xOffset"] = 6
	E.db["unitframe"]["units"]["raid2"]["raidRoleIcons"]["yOffset"] = 3
	E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["enable"] = true
	E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["font"] = "XvUI"
	E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["size"] = 24
	E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["yOffset"] = 10
	E.db["unitframe"]["units"]["raid2"]["readycheckIcon"]["position"] = "CENTER"
	E.db["unitframe"]["units"]["raid2"]["readycheckIcon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["raid2"]["resurrectIcon"]["attachTo"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["raid2"]["roleIcon"]["attachTo"] = "Frame"
	E.db["unitframe"]["units"]["raid2"]["roleIcon"]["enable"] = true
	E.db["unitframe"]["units"]["raid2"]["roleIcon"]["position"] = "TOPLEFT"
	E.db["unitframe"]["units"]["raid2"]["roleIcon"]["size"] = 16
	E.db["unitframe"]["units"]["raid2"]["roleIcon"]["xOffset"] = -8
	E.db["unitframe"]["units"]["raid2"]["roleIcon"]["yOffset"] = 8
	E.db["unitframe"]["units"]["raid2"]["width"] = 100
	E.db["unitframe"]["units"]["raid3"]["growthDirection"] = "RIGHT_UP"
	E.db["unitframe"]["units"]["raid3"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["raid3"]["height"] = 30
	E.db["unitframe"]["units"]["raid3"]["name"]["text_format"] = "[name:short:status]"
	E.db["unitframe"]["units"]["raid3"]["orientation"] = "RIGHT"
	E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["font"] = "XvUI"
	E.db["unitframe"]["units"]["tank"]["buffIndicator"]["enable"] = true
	E.db["unitframe"]["units"]["tank"]["height"] = 38
	E.db["unitframe"]["units"]["tank"]["name"]["text_format"] = "[name:short:status]"
	E.db["unitframe"]["units"]["tank"]["orientation"] = "RIGHT"
	E.db["unitframe"]["units"]["tank"]["rdebuffs"]["font"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["tank"]["rdebuffs"]["yOffset"] = 7
	E.db["unitframe"]["units"]["tank"]["targetsGroup"]["enable"] = false
	E.db["unitframe"]["units"]["tank"]["targetsGroup"]["height"] = 40
	E.db["unitframe"]["units"]["tank"]["targetsGroup"]["name"]["text_format"] = "[name:short:status]"
	E.db["unitframe"]["units"]["tank"]["targetsGroup"]["width"] = 100
	E.db["unitframe"]["units"]["tank"]["targetsGroup"]["xOffset"] = 5
	E.db["unitframe"]["units"]["tank"]["verticalSpacing"] = 3
	E.db["unitframe"]["units"]["tank"]["width"] = 100
	E.db["unitframe"]["units"]["target"]["aurabar"]["enable"] = false
	E.db["unitframe"]["units"]["target"]["buffIndicator"]["size"] = 16
	E.db["unitframe"]["units"]["target"]["buffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["target"]["buffs"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["target"]["buffs"]["growthX"] = "RIGHT"
	E.db["unitframe"]["units"]["target"]["buffs"]["height"] = 24
	E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["font"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["fontSize"] = 14
	E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["fontStyle"] = "SHADOW"
	E.db["unitframe"]["units"]["target"]["castbar"]["customTimeFont"]["font"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["target"]["castbar"]["customTimeFont"]["fontSize"] = 14
	E.db["unitframe"]["units"]["target"]["castbar"]["customTimeFont"]["fontStyle"] = "SHADOW"
	E.db["unitframe"]["units"]["target"]["castbar"]["height"] = 25
	E.db["unitframe"]["units"]["target"]["castbar"]["insideInfoPanel"] = false
	E.db["unitframe"]["units"]["target"]["castbar"]["textColor"]["b"] = 1
	E.db["unitframe"]["units"]["target"]["castbar"]["textColor"]["g"] = 1
	E.db["unitframe"]["units"]["target"]["castbar"]["textColor"]["r"] = 1
	E.db["unitframe"]["units"]["target"]["castbar"]["width"] = 250
	E.db["unitframe"]["units"]["target"]["debuffs"]["anchorPoint"] = "TOPLEFT"
	E.db["unitframe"]["units"]["target"]["debuffs"]["countFont"] = "Friz Quadrata TT"
	E.db["unitframe"]["units"]["target"]["debuffs"]["growthX"] = "RIGHT"
	E.db["unitframe"]["units"]["target"]["debuffs"]["height"] = 24
	E.db["unitframe"]["units"]["target"]["debuffs"]["maxDuration"] = 0
	E.db["unitframe"]["units"]["target"]["debuffs"]["priority"] = "Blacklist,Personal,nonPersonal,RaidDebuffs,CCDebuffs,Friendly:Dispellable"
	E.db["unitframe"]["units"]["target"]["disableMouseoverGlow"] = true
	E.db["unitframe"]["units"]["target"]["healPrediction"]["absorbStyle"] = "WRAPPED"
	E.db["unitframe"]["units"]["target"]["health"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["target"]["health"]["position"] = "BOTTOMLEFT"
	E.db["unitframe"]["units"]["target"]["health"]["text_format"] = "[perhp<%] || [health:current-nostatus:shortvalue]"
	E.db["unitframe"]["units"]["target"]["health"]["xOffset"] = 0
	E.db["unitframe"]["units"]["target"]["health"]["yOffset"] = -20
	E.db["unitframe"]["units"]["target"]["height"] = 45
	E.db["unitframe"]["units"]["target"]["name"]["position"] = "RIGHT"
	E.db["unitframe"]["units"]["target"]["name"]["text_format"] = "[name]"
	E.db["unitframe"]["units"]["target"]["name"]["xOffset"] = -10
	E.db["unitframe"]["units"]["target"]["orientation"] = "LEFT"
	E.db["unitframe"]["units"]["target"]["portrait"]["fullOverlay"] = true
	E.db["unitframe"]["units"]["target"]["portrait"]["overlay"] = true
	E.db["unitframe"]["units"]["target"]["portrait"]["paused"] = true
	E.db["unitframe"]["units"]["target"]["power"]["attachTextTo"] = "Frame"
	E.db["unitframe"]["units"]["target"]["power"]["detachFromFrame"] = true
	E.db["unitframe"]["units"]["target"]["power"]["detachedWidth"] = 120
	E.db["unitframe"]["units"]["target"]["power"]["height"] = 7
	E.db["unitframe"]["units"]["target"]["power"]["position"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["target"]["power"]["strataAndLevel"]["frameStrata"] = "MEDIUM"
	E.db["unitframe"]["units"]["target"]["power"]["text_format"] = "[powercolor][perpp<%]"
	E.db["unitframe"]["units"]["target"]["power"]["width"] = "spaced"
	E.db["unitframe"]["units"]["target"]["power"]["xOffset"] = 0
	E.db["unitframe"]["units"]["target"]["power"]["yOffset"] = -20
	E.db["unitframe"]["units"]["target"]["pvpIcon"]["anchorPoint"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["target"]["pvpIcon"]["scale"] = 0.75
	E.db["unitframe"]["units"]["target"]["pvpIcon"]["xOffset"] = 12
	E.db["unitframe"]["units"]["target"]["pvpIcon"]["yOffset"] = 12
	E.db["unitframe"]["units"]["target"]["width"] = 250
	E.db["unitframe"]["units"]["targettarget"]["debuffs"]["enable"] = false
	E.db["unitframe"]["units"]["targettarget"]["disableMouseoverGlow"] = true
	E.db["unitframe"]["units"]["targettarget"]["height"] = 30
	E.db["unitframe"]["units"]["targettarget"]["name"]["position"] = "RIGHT"
	E.db["unitframe"]["units"]["targettarget"]["name"]["text_format"] = "[name:abbrev:long]"
	E.db["unitframe"]["units"]["targettarget"]["name"]["xOffset"] = -10
	E.db["unitframe"]["units"]["targettarget"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["targettarget"]["raidicon"]["attachTo"] = "LEFT"
	E.db["unitframe"]["units"]["targettarget"]["raidicon"]["enable"] = false
	E.db["unitframe"]["units"]["targettarget"]["raidicon"]["xOffset"] = 2
	E.db["unitframe"]["units"]["targettarget"]["raidicon"]["yOffset"] = 0
	E.db["unitframe"]["units"]["targettarget"]["threatStyle"] = "GLOW"
	E.db["unitframe"]["units"]["targettarget"]["width"] = 135

	E.db["movers"]["AddonCompartmentMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-225,-225"
	E.db["movers"]["AlertFrameMover"] = "TOP,ElvUIParent,TOP,0,-20"
	E.db["movers"]["ArenaHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-254,-275"
	E.db["movers"]["AzeriteBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-245"
	E.db["movers"]["BNETMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-274"
	E.db["movers"]["BelowMinimapContainerMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-274"
	E.db["movers"]["BossBannerMover"] = "TOP,ElvUIParent,TOP,0,-125"
	E.db["movers"]["BossButton"] = "BOTTOM,UIParent,BOTTOM,0,100"
	E.db["movers"]["BossHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-254,-274"
	E.db["movers"]["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-250,-2"
	E.db["movers"]["ClassBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-328,380"
	E.db["movers"]["DebuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-250,-188"
	E.db["movers"]["DurabilityFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,141,-4"
	E.db["movers"]["ElvAB_1"] = "BOTTOM,UIParent,BOTTOM,0,40"
	E.db["movers"]["ElvAB_10"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,400"
	E.db["movers"]["ElvAB_13"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,484,40"
	E.db["movers"]["ElvAB_14"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-484,40"
	E.db["movers"]["ElvAB_15"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,230"
	E.db["movers"]["ElvAB_2"] = "BOTTOM,UIParent,BOTTOM,278,175"
	E.db["movers"]["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,0,81"
	E.db["movers"]["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,0,122"
	E.db["movers"]["ElvAB_5"] = "BOTTOM,ElvUIParent,BOTTOM,340,40"
	E.db["movers"]["ElvAB_6"] = "BOTTOM,ElvUIParent,BOTTOM,-340,40"
	E.db["movers"]["ElvAB_7"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,298"
	E.db["movers"]["ElvAB_8"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,332"
	E.db["movers"]["ElvAB_9"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,366"
	E.db["movers"]["ElvUF_AssistMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,5,-250"
	E.db["movers"]["ElvUF_FocusCastbarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-204,420"
	E.db["movers"]["ElvUF_FocusMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,470,340"
	E.db["movers"]["ElvUF_FocusTargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-204,370"
	E.db["movers"]["ElvUF_PartyMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,500,450"
	E.db["movers"]["ElvUF_PetCastbarMover"] = "TOPLEFT,ElvUF_Pet,BOTTOMLEFT,0,-1"
	E.db["movers"]["ElvUF_PetMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,612,285"
	E.db["movers"]["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-340,290"
	E.db["movers"]["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,-330,340"
	E.db["movers"]["ElvUF_Raid1Mover"] = "TOPLEFT,ElvUIParent,TOPLEFT,250,-413"
	E.db["movers"]["ElvUF_Raid2Mover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,190,450"
	E.db["movers"]["ElvUF_Raid3Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,43,230"
	E.db["movers"]["ElvUF_TankMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,600,-413"
	E.db["movers"]["ElvUF_TargetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,330,290"
	E.db["movers"]["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,330,340"
	E.db["movers"]["ElvUF_TargetTargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-470,340"
	E.db["movers"]["ElvUIBagMover"] = "BOTTOMRIGHT,RightChatPanel,BOTTOMRIGHT,0,26"
	E.db["movers"]["ElvUIBankMover"] = "BOTTOMLEFT,LeftChatPanel,BOTTOMLEFT,0,26"
	E.db["movers"]["EventToastMover"] = "TOP,ElvUIParent,TOP,0,-150"
	E.db["movers"]["ExperienceBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,5"
	E.db["movers"]["GMMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,250,-5"
	E.db["movers"]["HonorBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-251"
	E.db["movers"]["LootFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-612,-475"
	E.db["movers"]["LossControlMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,500"
	E.db["movers"]["MicrobarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-484,4"
	E.db["movers"]["MinimapClusterMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-2"
	E.db["movers"]["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-2"
	E.db["movers"]["MirrorTimer1Mover"] = "TOP,ElvUIParent,TOP,-1,-96"
	E.db["movers"]["MirrorTimer2Mover"] = "TOP,MirrorTimer1,BOTTOM,0,0"
	E.db["movers"]["MirrorTimer3Mover"] = "TOP,MirrorTimer2,BOTTOM,0,0"
	E.db["movers"]["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-163,-325"
	E.db["movers"]["PetAB"] = "BOTTOM,ElvUIParent,BOTTOM,0,163"
	E.db["movers"]["PlayerPowerBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,620,337"
	E.db["movers"]["PowerBarContainerMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,200"
	E.db["movers"]["PrivateAurasMover"] = "TOPRIGHT,ElvUI_MinimapHolder,BOTTOMLEFT,-10,-3"
	E.db["movers"]["PrivateRaidWarningMover"] = "TOP,RaidBossEmoteFrame,TOP,0,0"
	E.db["movers"]["QueueStatusMover"] = "BOTTOMRIGHT,ElvUI_MinimapHolder,BOTTOMRIGHT,-5,25"
	E.db["movers"]["ReputationBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-243"
	E.db["movers"]["RightChatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-3,3"
	E.db["movers"]["ShiftAB"] = "BOTTOM,ElvUIParent,BOTTOM,0,163"
	E.db["movers"]["SocialMenuMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-187"
	E.db["movers"]["TargetPowerBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-620,337"
	E.db["movers"]["ThreatBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,4"
	E.db["movers"]["TopCenterContainerMover"] = "TOP,ElvUIParent,TOP,0,-60"
	E.db["movers"]["TotemTrackerMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,485,163"
	E.db["movers"]["VOICECHAT"] = "TOPLEFT,ElvUIParent,TOPLEFT,250,-82"
	E.db["movers"]["VehicleLeaveButton"] = "BOTTOM,ElvUIParent,BOTTOM,0,110"
	E.db["movers"]["VehicleSeatMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,5,-320"
	E.db["movers"]["ZoneAbility"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-639,217"
end

function Private:Setup_ElvUI_GlobalDB()
	E.global["general"]["WorldMapCoordinates"]["position"] = "BOTTOMRIGHT"
	E.global["general"]["commandBarSetting"] = "DISABLED"
	E.global["general"]["fadeMapWhenMoving"] = false
	E.global["general"]["smallerWorldMap"] = false
end

function Private:Setup_ElvUI_PrivateDB()
	
	local isBagsEnabled = true
	
	local BAG_ADDONS = { "Bagnon", "BetterBags", "Baggins", "Sorted", "Inventorian", "Baganator", "ArkInventory", "OneBag3", "Combuctor" }
	
	for _, addon in ipairs(BAG_ADDONS) do
		if E:IsAddOnEnabled(addon) then isBagsEnabled = false end
	end
	
	E.private["bags"]["enable"] = isBagsEnabled
	E.private["nameplates"]["enable"] = false
	E.private["install_complete"] = E.version
	
	E.private["general"]["chatBubbleFont"] = "Friz Quadrata TT"
	E.private["general"]["chatBubbles"] = "disabled"
	E.private["general"]["dmgfont"] = "Friz Quadrata TT"
	E.private["general"]["glossTex"] = "XvUI"
	E.private["general"]["loot"] = false
	E.private["general"]["lootRoll"] = false
	E.private["general"]["namefont"] = "Friz Quadrata TT"
	E.private["general"]["nameplateFont"] = "Friz Quadrata TT"
	E.private["general"]["nameplateLargeFont"] = "Friz Quadrata TT"
	E.private["general"]["nameplateLargeFontSize"] = 12
	E.private["general"]["normTex"] = "XvUI"
	E.private["general"]["replaceBlizzFonts"] = false
	E.private["general"]["replaceCombatFont"] = false
	E.private["general"]["replaceNameFont"] = false
	E.private["general"]["replaceNameplateFont"] = false
	E.private["general"]["worldMap"] = false
	
	E.private["skins"]["blizzard"]["achievement"] = false
	E.private["skins"]["blizzard"]["addonManager"] = false
	E.private["skins"]["blizzard"]["adventureMap"] = false
	E.private["skins"]["blizzard"]["alertframes"] = false
	E.private["skins"]["blizzard"]["alliedRaces"] = false
	E.private["skins"]["blizzard"]["animaDiversion"] = false
	E.private["skins"]["blizzard"]["archaeology"] = false
	E.private["skins"]["blizzard"]["arena"] = false
	E.private["skins"]["blizzard"]["arenaRegistrar"] = false
	E.private["skins"]["blizzard"]["artifact"] = false
	E.private["skins"]["blizzard"]["auctionhouse"] = false
	E.private["skins"]["blizzard"]["azerite"] = false
	E.private["skins"]["blizzard"]["azeriteEssence"] = false
	E.private["skins"]["blizzard"]["azeriteRespec"] = false
	E.private["skins"]["blizzard"]["bags"] = false
	E.private["skins"]["blizzard"]["barber"] = false
	E.private["skins"]["blizzard"]["battlefield"] = false
	E.private["skins"]["blizzard"]["bgmap"] = false
	E.private["skins"]["blizzard"]["bgscore"] = false
	E.private["skins"]["blizzard"]["binding"] = false
	E.private["skins"]["blizzard"]["blizzardOptions"] = false
	E.private["skins"]["blizzard"]["bmah"] = false
	E.private["skins"]["blizzard"]["calendar"] = false
	E.private["skins"]["blizzard"]["channels"] = false
	E.private["skins"]["blizzard"]["character"] = false
	E.private["skins"]["blizzard"]["chromieTime"] = false
	E.private["skins"]["blizzard"]["collections"] = false
	E.private["skins"]["blizzard"]["communities"] = false
	E.private["skins"]["blizzard"]["contribution"] = false
	E.private["skins"]["blizzard"]["covenantPreview"] = false
	E.private["skins"]["blizzard"]["covenantRenown"] = false
	E.private["skins"]["blizzard"]["covenantSanctum"] = false
	E.private["skins"]["blizzard"]["craft"] = false
	E.private["skins"]["blizzard"]["deathRecap"] = false
	E.private["skins"]["blizzard"]["debug"] = false
	E.private["skins"]["blizzard"]["dressingroom"] = false
	E.private["skins"]["blizzard"]["editor"] = false
	E.private["skins"]["blizzard"]["encounterjournal"] = false
	E.private["skins"]["blizzard"]["engraving"] = false
	E.private["skins"]["blizzard"]["eventLog"] = false
	E.private["skins"]["blizzard"]["expansionLanding"] = false
	E.private["skins"]["blizzard"]["friends"] = false
	E.private["skins"]["blizzard"]["garrison"] = false
	E.private["skins"]["blizzard"]["gbank"] = false
	E.private["skins"]["blizzard"]["genericTrait"] = false
	E.private["skins"]["blizzard"]["gmChat"] = false
	E.private["skins"]["blizzard"]["gossip"] = false
	E.private["skins"]["blizzard"]["greeting"] = false
	E.private["skins"]["blizzard"]["guide"] = false
	E.private["skins"]["blizzard"]["guild"] = false
	E.private["skins"]["blizzard"]["guildBank"] = false
	E.private["skins"]["blizzard"]["guildcontrol"] = false
	E.private["skins"]["blizzard"]["guildregistrar"] = false
	E.private["skins"]["blizzard"]["help"] = false
	E.private["skins"]["blizzard"]["inspect"] = false
	E.private["skins"]["blizzard"]["islandQueue"] = false
	E.private["skins"]["blizzard"]["islandsPartyPose"] = false
	E.private["skins"]["blizzard"]["itemInteraction"] = false
	E.private["skins"]["blizzard"]["itemUpgrade"] = false
	E.private["skins"]["blizzard"]["lfg"] = false
	E.private["skins"]["blizzard"]["lfguild"] = false
	E.private["skins"]["blizzard"]["loot"] = false
	E.private["skins"]["blizzard"]["losscontrol"] = false
	E.private["skins"]["blizzard"]["macro"] = false
	E.private["skins"]["blizzard"]["mail"] = false
	E.private["skins"]["blizzard"]["majorFactions"] = false
	E.private["skins"]["blizzard"]["merchant"] = false
	E.private["skins"]["blizzard"]["mirrorTimers"] = false
	E.private["skins"]["blizzard"]["misc"] = false
	E.private["skins"]["blizzard"]["nonraid"] = false
	E.private["skins"]["blizzard"]["obliterum"] = false
	E.private["skins"]["blizzard"]["orderhall"] = false
	E.private["skins"]["blizzard"]["perks"] = false
	E.private["skins"]["blizzard"]["petbattleui"] = false
	E.private["skins"]["blizzard"]["petition"] = false
	E.private["skins"]["blizzard"]["playerChoice"] = false
	E.private["skins"]["blizzard"]["pvp"] = false
	E.private["skins"]["blizzard"]["quest"] = false
	E.private["skins"]["blizzard"]["questChoice"] = false
	E.private["skins"]["blizzard"]["raid"] = false
	E.private["skins"]["blizzard"]["reforge"] = false
	E.private["skins"]["blizzard"]["runeforge"] = false
	E.private["skins"]["blizzard"]["scrapping"] = false
	E.private["skins"]["blizzard"]["socket"] = false
	E.private["skins"]["blizzard"]["soulbinds"] = false
	E.private["skins"]["blizzard"]["spellbook"] = false
	E.private["skins"]["blizzard"]["stable"] = false
	E.private["skins"]["blizzard"]["subscriptionInterstitial"] = false
	E.private["skins"]["blizzard"]["tabard"] = false
	E.private["skins"]["blizzard"]["talent"] = false
	E.private["skins"]["blizzard"]["talkinghead"] = false
	E.private["skins"]["blizzard"]["taxi"] = false
	E.private["skins"]["blizzard"]["timemanager"] = false
	E.private["skins"]["blizzard"]["torghastLevelPicker"] = false
	E.private["skins"]["blizzard"]["trade"] = false
	E.private["skins"]["blizzard"]["tradeskill"] = false
	E.private["skins"]["blizzard"]["trainer"] = false
	E.private["skins"]["blizzard"]["transmogrify"] = false
	E.private["skins"]["blizzard"]["tutorials"] = false
	E.private["skins"]["blizzard"]["voidstorage"] = false
	E.private["skins"]["blizzard"]["weeklyRewards"] = false
	E.private["skins"]["blizzard"]["worldmap"] = false
	E.private["skins"]["parchmentRemoverEnable"] = true
	
	E.private["theme"] = "class"
end

function Private:Setup_ElvUI_ABB()
	if not E:IsAddOnEnabled('ElvUI_ActionBarBuddy') then Private:Print('ElvUI_ActionBarBuddy ' .. 'is not installed or enabled.') return end
	
	E.db["abb"]["bar1"]["customTriggers"] = true
	E.db["abb"]["bar1"]["displayTriggers"]["hasFocus"] = false
	E.db["abb"]["bar1"]["displayTriggers"]["hasTarget"] = false
	E.db["abb"]["bar1"]["displayTriggers"]["inCombat"] = 0
	E.db["abb"]["bar1"]["displayTriggers"]["inVehicle"] = false
	E.db["abb"]["bar1"]["displayTriggers"]["isDragonRiding"] = false
	E.db["abb"]["bar1"]["displayTriggers"]["isPlayerSpellsFrameOpen"] = true
	E.db["abb"]["bar1"]["displayTriggers"]["isPossessed"] = false
	E.db["abb"]["bar1"]["displayTriggers"]["isProfessionBookOpen"] = true
	E.db["abb"]["bar1"]["displayTriggers"]["notMaxHealth"] = false
	E.db["abb"]["bar1"]["displayTriggers"]["playerCasting"] = false
	E.db["abb"]["bar1"]["inheritGlobalFade"] = true
	E.db["abb"]["bar10"]["inheritGlobalFade"] = true
	E.db["abb"]["bar13"]["inheritGlobalFade"] = true
	E.db["abb"]["bar14"]["inheritGlobalFade"] = true
	E.db["abb"]["bar15"]["inheritGlobalFade"] = true
	E.db["abb"]["bar2"]["displayTriggers"]["hasFocus"] = false
	E.db["abb"]["bar2"]["displayTriggers"]["hasOverridebar"] = false
	E.db["abb"]["bar2"]["displayTriggers"]["hasTarget"] = false
	E.db["abb"]["bar2"]["displayTriggers"]["inCombat"] = 0
	E.db["abb"]["bar2"]["displayTriggers"]["inVehicle"] = false
	E.db["abb"]["bar2"]["displayTriggers"]["isDragonRiding"] = false
	E.db["abb"]["bar2"]["displayTriggers"]["isPossessed"] = false
	E.db["abb"]["bar2"]["displayTriggers"]["mouseover"] = false
	E.db["abb"]["bar2"]["displayTriggers"]["notMaxHealth"] = false
	E.db["abb"]["bar2"]["displayTriggers"]["playerCasting"] = false
	E.db["abb"]["bar2"]["inheritGlobalFade"] = true
	E.db["abb"]["bar3"]["inheritGlobalFade"] = true
	E.db["abb"]["bar4"]["inheritGlobalFade"] = true
	E.db["abb"]["bar5"]["inheritGlobalFade"] = true
	E.db["abb"]["bar6"]["inheritGlobalFade"] = true
	E.db["abb"]["bar7"]["inheritGlobalFade"] = true
	E.db["abb"]["bar8"]["inheritGlobalFade"] = true
	E.db["abb"]["bar9"]["inheritGlobalFade"] = true
	E.db["abb"]["barPet"]["inheritGlobalFade"] = true
	E.db["abb"]["global"]["displayTriggers"]["hasFocus"] = false
	E.db["abb"]["global"]["displayTriggers"]["hasOverridebar"] = false
	E.db["abb"]["global"]["displayTriggers"]["hasTarget"] = false
	E.db["abb"]["global"]["displayTriggers"]["inCombat"] = 0
	E.db["abb"]["global"]["displayTriggers"]["inVehicle"] = false
	E.db["abb"]["global"]["displayTriggers"]["isDragonRiding"] = false
	E.db["abb"]["global"]["displayTriggers"]["isPlayerSpellsFrameOpen"] = true
	E.db["abb"]["global"]["displayTriggers"]["isPossessed"] = false
	E.db["abb"]["global"]["displayTriggers"]["isProfessionBookOpen"] = true
	E.db["abb"]["global"]["displayTriggers"]["notMaxHealth"] = false
	E.db["abb"]["global"]["displayTriggers"]["playerCasting"] = false
	E.db["abb"]["global"]["globalFadeAlpha"] = 1
	E.db["abb"]["stanceBar"]["displayTriggers"]["inCombat"] = 1
	E.db["abb"]["stanceBar"]["inheritGlobalFade"] = true

	-- Update ElvUI
	E:StaggeredUpdateAll()

	-- Show message about layout being set
	PluginInstallStepComplete.message = "Layout Set"
	PluginInstallStepComplete:Show()
end

function Private:Setup_ElvUI_WeakAuras()
	if not E:IsAddOnEnabled('WeakAuras') then Private:Print('WeakAuras ' .. 'is not installed or enabled.') return end
	
	E.db["WeakAuras"]["cooldown"]["fonts"]["enable"] = true
	E.db["WeakAuras"]["cooldown"]["fonts"]["font"] = "Friz Quadrata TT"
	E.db["WeakAuras"]["cooldown"]["fonts"]["fontSize"] = 16
	E.db["WeakAuras"]["cooldown"]["hideBlizzard"] = true
end